
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 9.1.02 EDK_J_SP2.4
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_OPB_GPIO_0_DEVICE_ID,
		XPAR_OPB_GPIO_0_BASEADDR,
		XPAR_OPB_GPIO_0_INTERRUPT_PRESENT,
		XPAR_OPB_GPIO_0_IS_DUAL
	}
};


