
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 9.1.02 EDK_J_SP2.4
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xplbarb.h"

/*
* The configuration table for devices
*/

XPlbArb_Config XPlbArb_ConfigTable[] =
{
	{
		XPAR_PLB_BUS_DEVICE_ID,
		XPAR_PLB_BUS_BASEADDR,
		XPAR_PLB_BUS_PLB_NUM_MASTERS
	}
};


