
 PARAMETER VERSION = 2.2.0


BEGIN OS
 PARAMETER OS_NAME = standalone
 PARAMETER OS_VER = 1.00.a
 PARAMETER PROC_INSTANCE = ppc405_ppcjtag_chain
END

BEGIN OS
 PARAMETER OS_NAME = uCOS-II
 PARAMETER OS_VER = 2.86.a
 PARAMETER PROC_INSTANCE = ppc405_i
 PARAMETER APP_LOCATION = C:\Micrium\SOFTWARE\EvalBoards\Amirix\AP1000\GNU\EX1_OS\
 PARAMETER BSP_LOCATION = C:\Micrium\SOFTWARE\EvalBoards\Amirix\AP1000\GNU\BSP\
 PARAMETER OS_PORT_LOCATION = C:\Micrium\SOFTWARE\uCOS-II\Ports\PPC405\GNU\
 PARAMETER OS_SOURCE_LOCATION = C:\Micrium\SOFTWARE\uCOS-II\Source\
 PARAMETER OS_APP_HOOKS_EN = 0
 PARAMETER uC-Probe = false
 PARAMETER stdout = RS232_1
 PARAMETER stdin = RS232_1
 PARAMETER OS_TASK_STAT_EN = 0
 PARAMETER OS_LOWEST_PRIO = 15
 PARAMETER OS_MAX_TASKS = 15
 PARAMETER OS_Q_EN = 0
 PARAMETER OS_MUTEX_EN = 0
 PARAMETER OS_MEM_EN = 0
 PARAMETER OS_FLAG_EN = 0
END


BEGIN PROCESSOR
 PARAMETER HW_INSTANCE = ppc405_i
 PARAMETER DRIVER_NAME = cpu_ppc405
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER ARCHIVER = powerpc-eabi-ar
 PARAMETER CORE_CLOCK_FREQ_HZ = 240000000
 PARAMETER COMPILER = powerpc-eabi-gcc
END

BEGIN PROCESSOR
 PARAMETER DRIVER_NAME = cpu_ppc405
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = ppc405_ppcjtag_chain
END


BEGIN DRIVER
 PARAMETER HW_INSTANCE = plb2opb_bridge_i
 PARAMETER DRIVER_NAME = plb2opb
 PARAMETER DRIVER_VER = 1.00.a
END

BEGIN DRIVER
 PARAMETER HW_INSTANCE = opb_intc_i
 PARAMETER DRIVER_NAME = intc
 PARAMETER DRIVER_VER = 1.00.c
 PARAMETER USE_DCR = 0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartlite
 PARAMETER DRIVER_VER = 1.01.a
 PARAMETER HW_INSTANCE = RS232_1
END

BEGIN DRIVER
 PARAMETER HW_INSTANCE = plb_bus
 PARAMETER DRIVER_NAME = plbarb
 PARAMETER DRIVER_VER = 1.01.a
END

BEGIN DRIVER
 PARAMETER HW_INSTANCE = opb_bus
 PARAMETER DRIVER_NAME = opbarb
 PARAMETER DRIVER_VER = 1.02.a
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = opbslave_ext_bridge_i
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = emc
 PARAMETER DRIVER_VER = 2.00.a
 PARAMETER HW_INSTANCE = plb_emc_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 2.01.a
 PARAMETER HW_INSTANCE = opb_gpio_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = tmrctr
 PARAMETER DRIVER_VER = 1.00.b
 PARAMETER HW_INSTANCE = opb_timer_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = hwrtos
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = hwrtos_0
END


