
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 9.1.02 EDK_J_SP2.4
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xopbarb.h"

/*
* The configuration table for devices
*/

XOpbArb_Config XOpbArb_ConfigTable[] =
{
	{
		XPAR_OPB_BUS_DEVICE_ID,
		XPAR_OPB_BUS_BASEADDR,
		XPAR_OPB_BUS_NUM_MASTERS
	}
};


