
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 9.1.02 EDK_J_SP2.4
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xplb2opb.h"

/*
* The configuration table for devices
*/

XPlb2Opb_Config XPlb2Opb_ConfigTable[] =
{
	{
		XPAR_PLB2OPB_BRIDGE_I_DEVICE_ID,
		XPAR_PLB2OPB_BRIDGE_I_DCR_BASEADDR,
		XPAR_PLB2OPB_BRIDGE_I_PLB_NUM_MASTERS
	}
};


